"""
context_build.py — DETERMINISTIC context-pack generation (the amortization payoff).

context-amortization's rule is "no agent starts with a blank repo": every run begins
with a pack under .techne/context/ so workers don't re-derive the project. But nothing
GENERATED that pack — the files were hand-made and context_preflight only built a prompt
telling a host to write them. This derives the BASE pack from the repo itself, for free
(no model, no tokens), gated by the context hash so it's computed once and reused until
an input changes.

Derived deterministically:
  project_digest.md  — name, detected stack (stack_detect), top-level layout, README lead
  file_roles.md      — top-level dirs grouped with a one-line role + file counts
  commands.md        — test/build/lint commands detected from manifests
  risk_boundaries.md — default HITL boundaries + sensitive areas detected in the tree

NON-DESTRUCTIVE: an existing base file is preserved (it may be richer, hand-written);
pass force=True to regenerate. Model-driven enrichment can layer on later.
"""
from __future__ import annotations

import json
from pathlib import Path

from context_preflight import (
    BASE_FILES, CONTEXT_DIR, ensure_context_dir, context_status, write_context_hash,
)
from stack_detect import detect_stack

HARNESS_DIR = Path(__file__).parent
ROOT = HARNESS_DIR.parent

# Directory name → one-line role guess (kept deliberately small + generic).
_DIR_ROLES = {
    "harness": "pipeline engine + gates + RL",
    "skills": "routed skill cards (the discipline library)",
    "agents": "per-phase agent system prompts",
    "tests": "test suite",
    "src": "application source",
    "lib": "library code",
    "components": "UI components",
    "app": "application routes/pages",
    "docs": "documentation",
    "memory": "runtime ledgers (mistakes/reward/eval)",
    "scripts": "helper scripts",
    ".techne": "Techne runtime state (context packs, sessions)",
}


def _read(p: Path, limit: int = 4000) -> str:
    try:
        return p.read_text(encoding="utf-8")[:limit]
    except OSError:
        return ""


def _detect_commands(root: Path) -> dict[str, str]:
    """Best-effort test/build/lint/dev commands from common manifests."""
    cmds: dict[str, str] = {}
    pkg = root / "package.json"
    if pkg.exists():
        try:
            scripts = json.loads(pkg.read_text(encoding="utf-8")).get("scripts", {})
        except (json.JSONDecodeError, OSError):
            scripts = {}
        for purpose in ("test", "build", "lint", "dev", "typecheck", "start"):
            if purpose in scripts:
                cmds[purpose] = f"npm run {purpose}"
    # Python
    if (root / "pyproject.toml").exists() or (root / "pytest.ini").exists() or \
            any(root.glob("tests/test_*.py")):
        cmds.setdefault("test", "python -m pytest -q")
    if (root / "Makefile").exists():
        cmds.setdefault("make", "make <target>")
    return cmds


def _top_level(root: Path) -> list[Path]:
    out = []
    for p in sorted(root.iterdir()):
        if p.name.startswith(".") and p.name not in (".techne",):
            continue
        if p.name in ("node_modules", "__pycache__", "dist", "build", ".git"):
            continue
        out.append(p)
    return out


def _docs_index(root: Path) -> list[str]:
    """Canonical docs the context role keeps HOT (recall reads, conclude updates)."""
    docs = root / "docs"
    if not docs.is_dir():
        return []
    return sorted(p.relative_to(root).as_posix() for p in docs.rglob("*.md"))


def _project_digest(root: Path) -> str:
    stack = sorted(detect_stack(root)) or ["(no JS framework — likely Python/other)"]
    readme = ""
    for name in ("README.md", "readme.md", "README"):
        if (root / name).exists():
            lines = [l for l in _read(root / name, 1200).splitlines() if l.strip()][:8]
            readme = "\n".join(lines)
            break
    layout = "\n".join(
        f"  {p.name}{'/' if p.is_dir() else ''}" for p in _top_level(root)[:25]
    )
    docs = _docs_index(root)
    docs_block = "\n".join(f"  {d}" for d in docs) if docs else "  (no docs/ tree)"
    return (
        f"# Project Digest\n\n"
        f"**Repo:** {root.name}\n"
        f"**Stack (detected):** {', '.join(stack)}\n\n"
        f"## What it is\n\n{readme or '(no README found — fill in)'}\n\n"
        f"## Canonical docs (kept HOT — recall reads, conclude updates)\n\n{docs_block}\n\n"
        f"## Top-level layout\n\n{layout or '  (empty)'}\n\n"
        f"<!-- generated by harness/context_build.py — derived summary, regenerated on conclude -->\n"
    )


def _file_roles(root: Path) -> str:
    rows = []
    for p in _top_level(root):
        if not p.is_dir():
            continue
        count = sum(1 for _ in p.rglob("*") if _.is_file())
        role = _DIR_ROLES.get(p.name, "")
        rows.append(f"  {p.name + '/':22} {count:>4} files   {role}")
    body = "\n".join(rows) or "  (no subdirectories)"
    return f"# File Roles\n\nTop-level module map (file counts are a rough size signal):\n\n{body}\n"


def _commands_md(root: Path) -> str:
    cmds = _detect_commands(root)
    if cmds:
        body = "\n".join(f"  {purpose:10} {cmd}" for purpose, cmd in cmds.items())
    else:
        body = "  (none detected — fill in build/test/lint commands)"
    return f"# Commands\n\nDetected build/test/lint commands:\n\n{body}\n"


def _risk_boundaries(root: Path) -> str:
    detected = []
    checks = {
        "secrets/env": [".env", ".env.example", ".env.local"],
        "auth": ["auth", "middleware.ts", "middleware.js"],
        "deployment": ["netlify.toml", "Dockerfile", "docker-compose.yml", "vercel.json"],
        "database/schema": ["schema.sql", "firestore.rules", "prisma"],
    }
    for label, names in checks.items():
        if any((root / n).exists() for n in names) or any(root.glob(f"**/{names[0]}")):
            detected.append(label)
    flags = "\n".join(f"  - {d} present → HITL before changes" for d in detected) \
        or "  - (no sensitive areas auto-detected)"
    return (
        f"# Risk Boundaries\n\n"
        f"Human-in-the-loop required before touching:\n\n{flags}\n\n"
        f"Default no-go without explicit approval: secrets, production env, DNS/TLS,\n"
        f"destructive migrations, mass external sends.\n"
    )


_GENERATORS = {
    "project_digest.md": _project_digest,
    "file_roles.md": _file_roles,
    "commands.md": _commands_md,
    "risk_boundaries.md": _risk_boundaries,
}


def build_context(root: Path | str = ROOT, *, force: bool = False) -> dict:
    """Generate the base context pack for the repo at `root`.

    Writes each base file only if missing (or force=True) — existing hand-written files
    are preserved. Always refreshes context_hash.txt so the run sees a fresh pack.
    Returns {"written": [...], "skipped": [...], "hash": ...}.
    """
    root = Path(root).resolve()   # resolve so '.' yields a real repo name + stable globs
    ctx_dir = root / ".techne" / "context"
    ctx_dir.mkdir(parents=True, exist_ok=True)
    (ctx_dir / "context_packs").mkdir(parents=True, exist_ok=True)
    written, skipped = [], []
    for name in BASE_FILES:
        gen = _GENERATORS.get(name)
        if gen is None:
            continue
        dest = ctx_dir / name
        if dest.exists() and not force:
            skipped.append(name)
            continue
        dest.write_text(gen(root), encoding="utf-8")
        written.append(name)
    digest = write_context_hash(root)
    return {"written": written, "skipped": skipped, "hash": digest}


def ensure_context(root: Path | str = ROOT, *, force: bool = False) -> dict:
    """RECALL bookend: (re)build the base pack only when it's missing or stale, so the
    cost is paid once per change. Returns the build/skip report + freshness."""
    status = context_status(Path(root))
    needs = force or status["missing_base_files"] or not status["fresh"]
    if not needs:
        return {"ran": False, "reason": "fresh", "hash": status["current_hash"]}
    result = build_context(root, force=force)
    result["ran"] = True
    return result


# The deterministically-derived files reflect the repo's current state, so conclude
# regenerates them; risk_boundaries is policy (human-owned) and is preserved.
_DERIVED = ("project_digest.md", "file_roles.md", "commands.md")


def conclude_context(root: Path | str = ROOT) -> dict:
    """CONCLUDE bookend: keep the context HOT after a run. Regenerates the derived
    .techne/context summary from the now-current repo and bumps the hash, so the NEXT
    run's recall is fresh. Never touches docs/ — canonical prose docs (ARCHITECTURE,
    data-model, CONTRACTS…) are updated by the context AGENT (a model step); this is the
    deterministic half. Returns the refreshed files + the docs the agent should review."""
    root = Path(root).resolve()
    ctx_dir = root / ".techne" / "context"
    ctx_dir.mkdir(parents=True, exist_ok=True)
    refreshed = []
    for name in _DERIVED:
        gen = _GENERATORS.get(name)
        if gen is not None:
            (ctx_dir / name).write_text(gen(root), encoding="utf-8")
            refreshed.append(name)
    digest = write_context_hash(root)
    return {"refreshed": refreshed, "hash": digest, "docs_to_review": _docs_index(root)}


if __name__ == "__main__":
    import sys
    target = sys.argv[1] if len(sys.argv) > 1 else str(ROOT)
    force = "--force" in sys.argv
    rep = ensure_context(target, force=force)
    print(f"context @ {target}")
    for k, v in rep.items():
        print(f"  {k}: {v}")
