"""
prompt_evolution.py — Prompt variant selection and evolution.

Reads the reward log to determine which prompt variants produce the best
code for each task type. Over time, winning prompts get reused and losers
get retired. New variants can be generated by mutating winners.

This is the "policy" in the RL loop. The reward signal comes from
reward_log.py. The action space is which prompt variant to use.

Usage:
    from prompt_evolution import PromptEvolution

    evo = PromptEvolution(reward_log)

    # Select best prompt for a task type
    prompt = evo.select("auth")  # returns best variant or default

    # Record outcome (delegates to reward_log)
    evo.record_outcome(task_type="auth", variant="v2", ...)

    # Evolve: generate new variant from winner
    new_variant = evo.evolve("auth")

    # Dashboard
    print(evo.dashboard())
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from reward_log import RewardLog, WEIGHTS

HARNESS_DIR = Path(__file__).parent
ROOT = HARNESS_DIR.parent
AGENTS_DIR = ROOT / "agents"
MEMORY_DIR = ROOT / "memory"

# Default prompt variants (the starting point)
DEFAULT_VARIANTS = {
    "implementer": {
        "v1_strict": {
            "description": "Strict TDD — test first, minimal diff, no cleanup",
            "system_suffix": "\n\n# Hard Rules\n- Write the failing test FIRST\n- Minimum change only\n- No refactors outside scope",
            "temperature": 0.2,
        },
        "v2_pragmatic": {
            "description": "Pragmatic — implement + test, allow minor cleanup",
            "system_suffix": "\n\n# Guidelines\n- Write tests alongside implementation\n- Minimum change, but minor cleanup is OK\n- Focus on correctness over purity",
            "temperature": 0.3,
        },
        "v3_contextual": {
            "description": "Context-heavy — reads more files, considers architecture",
            "system_suffix": "\n\n# Approach\n- Read surrounding code for context before writing\n- Consider how this change affects nearby modules\n- Write tests that cover integration points, not just units",
            "temperature": 0.25,
        },
    },
    "critique": {
        "v1_conservative": {
            "description": "Conservative — only flag high-confidence issues",
            "system_suffix": "\n\n# Threshold\n- Only report findings you are >70% confident about\n- CRITICAL only if you're certain it will break in production",
            "temperature": 0.1,
        },
        "v2_aggressive": {
            "description": "Aggressive — flag everything suspicious",
            "system_suffix": "\n\n# Threshold\n- Report anything that could potentially be an issue\n- Include LOW findings for completeness\n- Better to over-report than miss a bug",
            "temperature": 0.3,
        },
    },
    "reviewer": {
        "v1_security": {
            "description": "Security-focused — XSS, injection, auth bypass first",
            "system_suffix": "\n\n# Priority Order\n1. Security (XSS, injection, auth bypass, secrets)\n2. Correctness (logic errors, null checks)\n3. Drift markers (TODO, console.log)",
            "temperature": 0.1,
        },
        "v2_correctness": {
            "description": "Correctness-focused — logic errors, edge cases first",
            "system_suffix": "\n\n# Priority Order\n1. Correctness (logic errors, boundary conditions, async)\n2. Security (XSS, injection)\n3. Style (drift markers, naming)",
            "temperature": 0.15,
        },
    },
}


@dataclass
class VariantStats:
    """Stats for a single prompt variant."""
    name: str
    task_type: str
    runs: int
    avg_score: float
    avg_critique: float
    avg_reviewer: float
    gate_pass_rate: float
    test_pass_rate: float


class PromptEvolution:
    """
    Manages prompt variants and selects the best one for each task type.

    The evolution loop:
    1. Start with default variants
    2. Record outcomes in reward_log
    3. After enough data, select winners
    4. Generate new variants by mutating winners
    5. New variants compete with old ones
    6. Losers get retired
    """

    def __init__(self, reward_log: RewardLog):
        self.reward_log = reward_log
        self.variants = dict(DEFAULT_VARIANTS)  # agent -> variant_name -> config

    def select(self, task_type: str, agent: str = "implementer") -> dict:
        """
        Select the best prompt variant for a task type.
        Returns the variant config dict.
        """
        best_name = self.reward_log.best_variant(task_type, min_runs=3)

        if best_name and best_name in self.variants.get(agent, {}):
            return self.variants[agent][best_name]

        # Not enough data or variant not found — use default
        agent_variants = self.variants.get(agent, {})
        if agent_variants:
            first_key = next(iter(agent_variants))
            return agent_variants[first_key]

        # Fallback: empty variant
        return {"description": "default", "system_suffix": "", "temperature": 0.2}

    def record_outcome(
        self,
        *,
        task_id: str,
        task_type: str,
        prompt_variant: str,
        gate_pass: bool,
        test_pass: bool,
        review_findings: list[str],
        critique_predictions: list[str],
        scope_clean: bool,
        attempt_count: int,
    ):
        """Record an outcome in the reward log."""
        self.reward_log.record(
            task_id=task_id,
            task_type=task_type,
            prompt_variant=prompt_variant,
            gate_pass=gate_pass,
            test_pass=test_pass,
            review_findings=review_findings,
            critique_predictions=critique_predictions,
            scope_clean=scope_clean,
            attempt_count=attempt_count,
        )

    def evolve(self, task_type: str, agent: str = "implementer") -> str:
        """
        Generate a new variant by mutating the current winner.
        Returns the new variant name.
        """
        winner_name = self.reward_log.best_variant(task_type, min_runs=3)
        if not winner_name or winner_name not in self.variants.get(agent, {}):
            # Not enough data to evolve
            return list(self.variants.get(agent, {}).keys())[0] if self.variants.get(agent) else "v1"

        winner = self.variants[agent][winner_name]

        # Get critique blind spots to inform mutation
        misses = self.reward_log.critique_misses(min_count=2)
        blind_spot_hint = ""
        if misses and agent == "critique":
            blind_spot_hint = f"\n- Also check for: {misses[0]['pattern'][:60]}"

        # Generate new variant by mutating
        new_name = f"{winner_name}_evolved"
        new_suffix = winner.get("system_suffix", "") + blind_spot_hint

        # Adjust temperature based on score
        scores = self.reward_log.variant_scores(task_type)
        winner_score = next(
            (s["avg_score"] for s in scores if s["prompt_variant"] == winner_name),
            0.5,
        )
        # If score is low, try higher temperature (more exploration)
        # If score is high, keep temperature low (exploit)
        new_temp = winner.get("temperature", 0.2)
        if winner_score < 0.6:
            new_temp = min(0.5, new_temp + 0.1)
        elif winner_score > 0.8:
            new_temp = max(0.1, new_temp - 0.05)

        self.variants.setdefault(agent, {})[new_name] = {
            "description": f"Evolved from {winner_name}",
            "system_suffix": new_suffix,
            "temperature": new_temp,
        }

        return new_name

    def retire_losers(self, task_type: str, agent: str = "implementer", min_runs: int = 5):
        """
        Remove variants that consistently score poorly.
        Keeps at least 2 variants per agent.
        """
        scores = self.reward_log.variant_scores(task_type)
        agent_variants = self.variants.get(agent, {})

        if len(agent_variants) <= 2:
            return  # don't retire below 2

        # Find variants with score < 0.4 after enough runs
        for s in scores:
            if s["cnt"] >= min_runs and s["avg_score"] < 0.4:
                name = s["prompt_variant"]
                if name in agent_variants and len(agent_variants) > 2:
                    del agent_variants[name]

    def get_variant_prompt(
        self,
        task_type: str,
        agent: str,
        base_system: str,
    ) -> tuple[str, float]:
        """
        Get the full system prompt and temperature for the best variant.
        Returns (system_prompt, temperature).
        """
        variant = self.select(task_type, agent)
        system = base_system + variant.get("system_suffix", "")
        temperature = variant.get("temperature", 0.2)
        return system, temperature

    def dashboard(self) -> str:
        """Human-readable evolution status."""
        types = self.reward_log.all_task_types()
        lines = [
            "=" * 55,
            "PROMPT EVOLUTION",
            "=" * 55,
        ]

        for agent, variants in self.variants.items():
            lines.append(f"\n{agent.upper()} variants ({len(variants)}):")
            for name, config in variants.items():
                lines.append(
                    f"  {name:25}  temp={config.get('temperature', 0.2):.2f}  "
                    f"{config.get('description', '')[:40]}"
                )

        if types:
            lines.append("\nWINNERS BY TASK TYPE:")
            for t in types:
                for agent in self.variants:
                    best = self.reward_log.best_variant(t)
                    if best:
                        lines.append(f"  {t:12} / {agent:12} → {best}")

        lines.append("=" * 55)
        return "\n".join(lines)


if __name__ == "__main__":
    import os
    log = RewardLog("/tmp/test_evo.db")
    evo = PromptEvolution(log)

    # Record some outcomes
    for i in range(5):
        log.record(
            task_id=f"t{i}", task_type="auth",
            prompt_variant="v1_strict" if i < 3 else "v2_pragmatic",
            gate_pass=True, test_pass=True,
            review_findings=[] if i < 3 else ["minor issue"],
            critique_predictions=[],
            scope_clean=True, attempt_count=1,
        )

    # Select best
    best = evo.select("auth", "implementer")
    print(f"Best variant for auth: {best}")

    # Evolve
    new = evo.evolve("auth", "implementer")
    print(f"Evolved to: {new}")

    print(f"\n{evo.dashboard()}")

    log.close()
    os.remove("/tmp/test_evo.db")
    print("\nPrompt evolution: OK")
