"""
prompt_evolution.py — Prompt variant selection and evolution.

Reads the reward log to determine which prompt variants produce the best
code for each task type. Over time, winning prompts get reused and losers
get retired. New variants can be generated by mutating winners.

This is the "policy" in the RL loop. The reward signal comes from
reward_log.py. The action space is which prompt variant to use.

Usage:
    from prompt_evolution import PromptEvolution

    evo = PromptEvolution(reward_log)

    # Select best prompt for a task type
    prompt = evo.select("auth")  # returns best variant or default

    # Record outcome (delegates to reward_log)
    evo.record_outcome(task_type="auth", variant="v2", ...)

    # Evolve: generate new variant from winner
    new_variant = evo.evolve("auth")

    # Dashboard
    print(evo.dashboard())
"""

from __future__ import annotations

import copy
import json
import subprocess
import sys
import uuid
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Callable, Optional

from reward_log import RewardLog, WEIGHTS

HARNESS_DIR = Path(__file__).parent
ROOT = HARNESS_DIR.parent
AGENTS_DIR = ROOT / "agents"
MEMORY_DIR = ROOT / ".techne" / "memory"
DEFAULT_PROPOSALS_PATH = MEMORY_DIR / "prompt_proposals.json"
VARIANTS_FILE = MEMORY_DIR / "prompt_variants.json"
EVAL_RUNNER = ROOT / "tests" / "evals" / "run_evals.py"

# Default prompt variants (the starting point)
DEFAULT_VARIANTS = {
    "implementer": {
        "v1_strict": {
            "description": "Strict TDD — test first, minimal diff, no cleanup",
            "system_suffix": "\n\n# Hard Rules\n- Write the failing test FIRST\n- Minimum change only\n- No refactors outside scope",
            "temperature": 0.2,
        },
        "v2_pragmatic": {
            "description": "Pragmatic — implement + test, allow minor cleanup",
            "system_suffix": "\n\n# Guidelines\n- Write tests alongside implementation\n- Minimum change, but minor cleanup is OK\n- Focus on correctness over purity",
            "temperature": 0.3,
        },
        "v3_contextual": {
            "description": "Context-heavy — reads more files, considers architecture",
            "system_suffix": "\n\n# Approach\n- Read surrounding code for context before writing\n- Consider how this change affects nearby modules\n- Write tests that cover integration points, not just units",
            "temperature": 0.25,
        },
    },
    "critique": {
        "v1_conservative": {
            "description": "Conservative — only flag high-confidence issues",
            "system_suffix": "\n\n# Threshold\n- Only report findings you are >70% confident about\n- CRITICAL only if you're certain it will break in production",
            "temperature": 0.1,
        },
        "v2_aggressive": {
            "description": "Aggressive — flag everything suspicious",
            "system_suffix": "\n\n# Threshold\n- Report anything that could potentially be an issue\n- Include LOW findings for completeness\n- Better to over-report than miss a bug",
            "temperature": 0.3,
        },
    },
    "reviewer": {
        "v1_security": {
            "description": "Security-focused — XSS, injection, auth bypass first",
            "system_suffix": "\n\n# Priority Order\n1. Security (XSS, injection, auth bypass, secrets)\n2. Correctness (logic errors, null checks)\n3. Drift markers (TODO, console.log)",
            "temperature": 0.1,
        },
        "v2_correctness": {
            "description": "Correctness-focused — logic errors, edge cases first",
            "system_suffix": "\n\n# Priority Order\n1. Correctness (logic errors, boundary conditions, async)\n2. Security (XSS, injection)\n3. Style (drift markers, naming)",
            "temperature": 0.15,
        },
    },
}


@dataclass
class VariantStats:
    """Stats for a single prompt variant."""
    name: str
    task_type: str
    runs: int
    avg_score: float
    avg_critique: float
    avg_reviewer: float
    gate_pass_rate: float
    test_pass_rate: float


@dataclass
class Proposal:
    """
    A staged prompt mutation awaiting validation and human ratification.

    A proposal never affects which prompt is used until it is ratified. This is
    the firewall against score-driven auto-edits: the system may *propose* a full
    rewrite, but recurrence (propose), a structural gate (validate), and a human
    (ratify) must all agree before it joins the active pool.

    status transitions:
        pending → validated → ratified   (the happy path)
        pending → rejected                (failed the structural gate)
        validated → rejected              (human declined)
    """
    id: str
    task_type: str
    agent: str
    base_variant: str          # the winner this was mutated from
    variant_name: str          # proposed new variant name
    config: dict               # description / system_suffix / temperature
    status: str = "pending"    # pending | validated | rejected | ratified
    candidate_score: float = 0.0
    incumbent_score: float = 0.0
    created: str = ""
    ratified_by: str = ""

    def __post_init__(self):
        if not self.created:
            self.created = datetime.now(timezone.utc).isoformat()


class PromptEvolution:
    """
    Manages prompt variants and selects the best one for each task type.

    The evolution loop:
    1. Start with default variants
    2. Record outcomes in reward_log
    3. After enough data, select winners
    4. Generate new variants by mutating winners
    5. New variants compete with old ones
    6. Losers get retired
    """

    def __init__(self, reward_log: RewardLog, proposals_path: str | Path | None = None,
                 variants_path: str | Path | None = None):
        self.reward_log = reward_log
        # Deep copy: promotion mutates self.variants, must not leak into the
        # module-level DEFAULT_VARIANTS or bleed across instances.
        self.variants = copy.deepcopy(DEFAULT_VARIANTS)  # agent -> variant_name -> config
        self.proposals_path = Path(proposals_path or DEFAULT_PROPOSALS_PATH)
        self.variants_path = Path(variants_path or VARIANTS_FILE)
        # Load any previously-ratified variants on top of defaults so that
        # ratified prompt variants survive process restart.
        self._load_variants()

    def select(self, task_type: str, agent: str = "implementer") -> dict:
        """
        Select the best prompt variant for a task type.
        Returns the variant config dict.
        """
        best_name = self.reward_log.best_variant(task_type, min_runs=3)

        if best_name and best_name in self.variants.get(agent, {}):
            return self.variants[agent][best_name]

        # Not enough data or variant not found — use default
        agent_variants = self.variants.get(agent, {})
        if agent_variants:
            first_key = next(iter(agent_variants))
            return agent_variants[first_key]

        # Fallback: empty variant
        return {"description": "default", "system_suffix": "", "temperature": 0.2}

    def record_outcome(
        self,
        *,
        task_id: str,
        task_type: str,
        prompt_variant: str,
        gate_pass: bool,
        test_pass: bool,
        review_findings: list[str],
        critique_predictions: list[str],
        scope_clean: bool,
        attempt_count: int,
    ):
        """Record an outcome in the reward log."""
        self.reward_log.record(
            task_id=task_id,
            task_type=task_type,
            prompt_variant=prompt_variant,
            gate_pass=gate_pass,
            test_pass=test_pass,
            review_findings=review_findings,
            critique_predictions=critique_predictions,
            scope_clean=scope_clean,
            attempt_count=attempt_count,
        )

    def _mutate_winner(
        self, task_type: str, agent: str = "implementer"
    ) -> Optional[tuple[str, str, dict]]:
        """
        Mutate the current winner into a candidate variant config.

        Returns (base_variant, new_name, config) or None when there is not
        enough data to evolve (the recurrence gate — best_variant needs
        min_runs). Pure: touches neither the active pool nor the proposals log.
        """
        winner_name = self.reward_log.best_variant(task_type, min_runs=3)
        if not winner_name or winner_name not in self.variants.get(agent, {}):
            return None

        winner = self.variants[agent][winner_name]

        # Get critique blind spots to inform mutation
        misses = self.reward_log.critique_misses(min_count=2)
        blind_spot_hint = ""
        if misses and agent == "critique":
            blind_spot_hint = f"\n- Also check for: {misses[0]['pattern'][:60]}"

        new_name = f"{winner_name}_evolved"
        new_suffix = winner.get("system_suffix", "") + blind_spot_hint

        # Adjust temperature based on score: low score → explore, high → exploit.
        scores = self.reward_log.variant_scores(task_type)
        winner_score = next(
            (s["avg_score"] for s in scores if s["prompt_variant"] == winner_name),
            0.5,
        )
        new_temp = winner.get("temperature", 0.2)
        if winner_score < 0.6:
            new_temp = min(0.5, new_temp + 0.1)
        elif winner_score > 0.8:
            new_temp = max(0.1, new_temp - 0.05)

        config = {
            "description": f"Evolved from {winner_name}",
            "system_suffix": new_suffix,
            "temperature": new_temp,
        }
        return winner_name, new_name, config

    def propose(self, task_type: str, agent: str = "implementer") -> Optional[Proposal]:
        """
        Stage a mutation of the current winner as a Proposal.

        Returns the staged Proposal, or None when the recurrence gate is not
        met. The proposal is persisted but NOT added to the active pool — it
        cannot affect prompt selection until validate() + ratify() promote it.
        """
        mutated = self._mutate_winner(task_type, agent)
        if mutated is None:
            return None
        base_variant, new_name, config = mutated

        # Idempotent while open: post_run_evolve calls propose() every cycle, so
        # don't stack duplicates. Reuse an existing un-resolved proposal for the
        # same (agent, variant_name). Resolved ones (rejected/ratified) don't block.
        for existing in self._load_proposals():
            if (existing.agent == agent
                    and existing.variant_name == new_name
                    and existing.status in ("pending", "validated")):
                return existing

        proposal = Proposal(
            id=uuid.uuid4().hex[:12],
            task_type=task_type,
            agent=agent,
            base_variant=base_variant,
            variant_name=new_name,
            config=config,
            incumbent_score=self._incumbent_score(task_type, base_variant),
        )
        self._save_proposal(proposal)
        return proposal

    def validate(
        self,
        proposal: Proposal,
        scorer: Optional[Callable[[dict], float]] = None,
    ) -> Proposal:
        """
        Structural gate: score the candidate and mark it validated or rejected.

        `scorer(config) -> float` is the seam where a per-variant evaluator
        plugs in. The default runs the eval suite and reports a coarse
        pass/fail regression signal (1.0 if the suite passes, else 0.0) — it
        confirms the candidate does not ship against a red suite, it does NOT
        prove the variant is better. Supply a custom scorer for that.

        Never promotes — passing validation only makes a proposal eligible for
        ratification.
        """
        scorer = scorer or self._default_scorer
        proposal.candidate_score = float(scorer(proposal.config))
        proposal.status = (
            "validated"
            if proposal.candidate_score >= proposal.incumbent_score
            else "rejected"
        )
        self._save_proposal(proposal)
        return proposal

    def ratify(self, proposal_id: str, approved: bool, by: str = "human") -> bool:
        """
        Human ratification — the only path that promotes a proposal.

        Promotes into the active pool ONLY when the proposal exists, was
        structurally validated, and the human approved it. Any other case
        leaves the active pool untouched and returns False. This enforces all
        three gates together: recurrence (propose) + structural (validate) +
        human (ratify).
        """
        proposal = self.get_proposal(proposal_id)
        if proposal is None:
            return False

        if not approved:
            proposal.status = "rejected"
            proposal.ratified_by = by
            self._save_proposal(proposal)
            return False

        if proposal.status != "validated":
            # Structurally-gated: cannot promote what history hasn't cleared.
            return False

        self.variants.setdefault(proposal.agent, {})[proposal.variant_name] = proposal.config
        proposal.status = "ratified"
        proposal.ratified_by = by
        self._save_proposal(proposal)
        self._save_variants()
        return True

    def evolve(self, task_type: str, agent: str = "implementer") -> str:
        """
        Back-compat shim. Stages a proposal (no longer auto-activates).

        Returns the proposed variant name, or the current best/default name when
        there is nothing to evolve. Promotion now requires validate() + ratify().
        """
        proposal = self.propose(task_type, agent)
        if proposal is not None:
            return proposal.variant_name
        agent_variants = self.variants.get(agent, {})
        return next(iter(agent_variants)) if agent_variants else "v1"

    # ── Proposal persistence + scoring ───────────────────────────────────

    def _save_variants(self) -> None:
        """Persist the current variant pool to disk so ratified variants survive restart."""
        self.variants_path.parent.mkdir(parents=True, exist_ok=True)
        self.variants_path.write_text(
            json.dumps(self.variants, indent=2, default=str),
            encoding="utf-8",
        )

    def _load_variants(self) -> None:
        """Load previously-ratified variants from disk and merge on top of defaults.

        Per-agent variants loaded from disk override defaults for the same
        variant name. Variants that only exist on disk (ratified in a prior
        session) are added. Default variants that were never overridden are kept.
        """
        if not self.variants_path.exists():
            return
        try:
            saved = json.loads(self.variants_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return
        for agent, variants in saved.items():
            self.variants.setdefault(agent, {}).update(variants)

    def _incumbent_score(self, task_type: str, variant: str) -> float:
        """Recorded avg composite score of the incumbent variant (default 0.5)."""
        scores = self.reward_log.variant_scores(task_type)
        return next(
            (s["avg_score"] for s in scores if s["prompt_variant"] == variant),
            0.5,
        )

    def _default_scorer(self, config: dict) -> float:
        """Coarse structural gate: 1.0 if the eval suite passes, else 0.0."""
        if not EVAL_RUNNER.exists():
            return 0.0
        try:
            proc = subprocess.run(
                [sys.executable, "-X", "utf8", str(EVAL_RUNNER)],
                capture_output=True, cwd=str(ROOT), timeout=600,
            )
            return 1.0 if proc.returncode == 0 else 0.0
        except (subprocess.SubprocessError, OSError):
            return 0.0

    def _load_proposals(self) -> list[Proposal]:
        if not self.proposals_path.exists():
            return []
        try:
            raw = json.loads(self.proposals_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return []
        return [Proposal(**d) for d in raw]

    def _save_proposal(self, proposal: Proposal) -> None:
        """Upsert a proposal into the log by id."""
        proposals = [p for p in self._load_proposals() if p.id != proposal.id]
        proposals.append(proposal)
        self.proposals_path.parent.mkdir(parents=True, exist_ok=True)
        self.proposals_path.write_text(
            json.dumps([asdict(p) for p in proposals], indent=2),
            encoding="utf-8",
        )

    def get_proposal(self, proposal_id: str) -> Optional[Proposal]:
        return next((p for p in self._load_proposals() if p.id == proposal_id), None)

    def list_proposals(self, status: Optional[str] = None) -> list[Proposal]:
        proposals = self._load_proposals()
        if status is not None:
            proposals = [p for p in proposals if p.status == status]
        return proposals

    def retire_losers(self, task_type: str, agent: str = "implementer", min_runs: int = 5):
        """
        Remove variants that consistently score poorly.
        Keeps at least 2 variants per agent.
        """
        scores = self.reward_log.variant_scores(task_type)
        agent_variants = self.variants.get(agent, {})

        if len(agent_variants) <= 2:
            return  # don't retire below 2

        # Find variants with score < 0.4 after enough runs
        for s in scores:
            if s["cnt"] >= min_runs and s["avg_score"] < 0.4:
                name = s["prompt_variant"]
                if name in agent_variants and len(agent_variants) > 2:
                    del agent_variants[name]

    def get_variant_prompt(
        self,
        task_type: str,
        agent: str,
        base_system: str,
    ) -> tuple[str, float]:
        """
        Get the full system prompt and temperature for the best variant.
        Returns (system_prompt, temperature).
        """
        variant = self.select(task_type, agent)
        system = base_system + variant.get("system_suffix", "")
        temperature = variant.get("temperature", 0.2)
        return system, temperature

    def dashboard(self) -> str:
        """Human-readable evolution status."""
        types = self.reward_log.all_task_types()
        lines = [
            "=" * 55,
            "PROMPT EVOLUTION",
            "=" * 55,
        ]

        for agent, variants in self.variants.items():
            lines.append(f"\n{agent.upper()} variants ({len(variants)}):")
            for name, config in variants.items():
                lines.append(
                    f"  {name:25}  temp={config.get('temperature', 0.2):.2f}  "
                    f"{config.get('description', '')[:40]}"
                )

        if types:
            lines.append("\nWINNERS BY TASK TYPE:")
            for t in types:
                for agent in self.variants:
                    best = self.reward_log.best_variant(t)
                    if best:
                        lines.append(f"  {t:12} / {agent:12} → {best}")

        lines.append("=" * 55)
        return "\n".join(lines)


if __name__ == "__main__":
    import os
    log = RewardLog("/tmp/test_evo.db")
    # Use a temp proposals file so the self-test never writes to real memory/.
    evo = PromptEvolution(log, proposals_path="/tmp/test_evo_proposals.json")

    # Record some outcomes
    for i in range(5):
        log.record(
            task_id=f"t{i}", task_type="auth",
            prompt_variant="v1_strict" if i < 3 else "v2_pragmatic",
            gate_pass=True, test_pass=True,
            review_findings=[] if i < 3 else ["minor issue"],
            critique_predictions=[],
            scope_clean=True, attempt_count=1,
        )

    # Select best
    best = evo.select("auth", "implementer")
    print(f"Best variant for auth: {best}")

    # Evolve
    new = evo.evolve("auth", "implementer")
    print(f"Evolved to: {new}")

    print(f"\n{evo.dashboard()}")

    log.close()
    os.remove("/tmp/test_evo.db")
    if os.path.exists("/tmp/test_evo_proposals.json"):
        os.remove("/tmp/test_evo_proposals.json")
    print("\nPrompt evolution: OK")
